spring:
  application:
    name: restapi

  profiles:
    active: dev

  datasource:
    url: ${DB_CONNECTION}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  flyway:
    enabled: false

server:
  port: ${CONTAINER_PORT}

springdoc:
  api-docs:
    path: /api-docs # Đường dẫn OpenAPI
  swagger-ui:
    path: /swagger-ui.html # Đường dẫn Swagger UI
